version: 2.1

executors:
  golang:
    docker:
      - image: circleci/golang:1.14
    environment:
      GO111MODULE: "on"

commands:
  build:
    parameters:
      app_name:
        type: string
    steps:
      - run:
          name: Build << parameters.app_name >> binary
          command: |
            cd cmd/<< parameters.app_name >> || exit 1
            go build
jobs:
  build:
    executor: golang
    steps:
      - checkout
      - build:
          app_name: gensymbols
      - build:
          app_name: runsim
      - build:
          app_name: execmgmt
      - build:
          app_name: slack
      - build:
          app_name: github
      - build:
          app_name: cmpsemver

workflows:
  version: 2
  build-binaries:
    jobs:
      - build
